### ISSUE TITLE
user can see their car

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Put image tag position at the top left of the page with car inside
- [x] Set background color
- [x] Fix all errors
