### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Make four CSS classes that rotate the car up, down, left and right
- [x] Make conditionals that change the image class when the corresponding arrow key is pushed
- [x] When pressing up arrow car turns up, down arrow turns car down, left arrow turns left, right arrow turns right 
- [x] Fix all errors
