### ISSUE TITLE
user can start their car

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create an object holding the cars x and y values.
- [x] Give the car image absolute positioning.
- [x] Create a function that changes the cars top and left offsets when space is pushed.
- [x] Set the cars function to happen every 16 milliseconds while space is pushed.
- [x] Fix all errors.
