### ISSUE TITLE
user can stop their car

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Make a property in the car object that indicates if the car is moving or not.
- [x] Make a property in car to place the interval id.
- [x] Create a conditional that clears or sets the interval depending on the status of car object.
- [x] Fix all errors.
