### ISSUE TITLE
user can steer their car

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add a property in the car object that keeps track of the direction the car is facing.
- [x] Add a conditional in interval function that changes the x and y in car depending on the car object direction.
- [x] Check that when the car faces left it moves left and when car faces down it moves down etc.
- [x] Fix all errors.
